### ISSUE TITLE
Set BrandID in Docusign envelop

### ISSUE THREAD

**Issue by meeramanesh** [docusign/mobile-android-sdk#27]
How can I set the brand id in the envelop? iOS SDK can  do that by DSMEnvelopTemplate
I am using the below code in the application 

 val builder = DSEnvelope.Builder()
                .envelopeName(envelopeName)
                .document(
                    DSDocument.Builder()
                        .documentId(documentInfo.id)
                        .uri(documentInfo.path)
                        .name(documentInfo.name)
                        .build()
                )

**Comment by naveentds** [comment]
Hi @meeramanesh Thanks for posting the issue.
We will add this feature to our feature SDK Roadmap and will be available in future SDK releases.

**Comment by naveentds** [comment]
HI @meeramanesh  DocuSign Android SDK v1.5.3 has been released.
We added the support for setting brand Id in this release.

- If you are creating envelope using DSEnvelope Builder,  you can set brandId as follows:

```
val builder = DSEnvelope.Builder()
.envelopeName(envelopeName)
.document(
DSDocument.Builder()
.documentId(documentInfo.id)
.uri(documentInfo.path)
.name(documentInfo.name)
.brandId(brandId)
.build()
)
```
- In order to apply branding that is set using brandId in Online Signing, you need to invoke the following API:
```
DocuSign.getInstance().getCustomSettingsDelegate().disableNativeComponentsInOnlineSigning(applicationContext, true)
``` 
This will launch embedded Online Signing ceremony with branding and does not use Native components. This UI will be different compared to regular Online Signing ceremony which uses Native components.
- Instead if you would like to use regular Online Signing with native components and still apply branding, then, invoke our SDK's branding API as follows:
```
DSAppearanceDelegate appearanceDelegate = DocuSign.getInstance().getAppearanceDelegate();
            DSAppearance appearance = new DSAppearance.Builder()
                    .setActionBarColor(new ColorDrawable(getResources().getColor(R.color.colorDocuSignPrimary1)))
                    .setStatusBarColor(new ColorDrawable(getResources().getColor(R.color.colorDocuSignPrimaryDark1)))
                    .setActionBarLogo(getResources().getDrawable(R.drawable.ic_save_offline))
                    .setActionBarTitleTextColor(new ColorDrawable(getResources().getColor(R.color.color_black)))
                    .setBottomToolbarColor(new ColorDrawable(getResources().getColor(R.color.ds_yellow)))
                    .setBottomToolbarButtonColor(new ColorDrawable(getResources().getColor(R.color.ds_more_dark_blue)))
                    .setBottomToolbarButtonTextColor(new ColorDrawable(getResources().getColor(R.color.ds_white)))
                    .setBottomToolbarDocuSignImageVisibility(brandingCheckBox.isChecked())
                    .build();
            appearanceDelegate.setAppearance(appearance);
```
In this case, brandId won't be applicable.
