### ISSUE TITLE
Sign Online method did not working 

### ISSUE THREAD

**Issue by yusufonderd** [docusign/mobile-android-sdk#31]
Sdk version : 1.5.3

I'm using this function when trying to sign envelope with envelope ID. 

  ```
val signingDelegate = DocuSign.getInstance().getSigningDelegate()
        signingDelegate.signOnline(context, envelopeId, object :
            DSOnlineSigningListener {
....
     })
```
But docusign signuture dialog did not open. Only onSuccess method triggered. I can't seen additional signuture dialog. How can I start the signing process ?

**Comment by naveentds** [comment]
Can you let me know how you created the envelope? The envelope which is created should be existing in DocuSign server is you are using ```signOnline()``` API in SDK.
If you created envelope locally, then you can invoke ```createEnvelopeAndLaunchOnlineSigning()``` API.

Were you able to see the signing flow and document is displayed for signing? 
In order to use ```signOnline()``` API, can you make sure you were authenticated with DocuSign by invoking SDK's ```login()```  API. 
Can you let us know the AccountId so that we can also check telemetry on our side for debugging the issue.

**Comment by yusufonderd** [comment]
I use launchCaptiveSigning method for starting signing. It fixed my problem. Thank you.
